config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  get 'comments/create'
  # resources :posts
  root to: 'home#index'
  devise_for :users , :controllers => {:registrations => "registrations"}
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    paginates_per 6
    has_one_attached :image
    validates :content, presence: true
    validates :categories, presence: true
    validates :image, presence: true
    validates :tittle, presence: true
    belongs_to :user

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :email,uniqueness: true
         has_many :posts , dependent: :delete_all
         validates :first_name, presence: true
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 

    def sign_up_params
      devise_parameter_sanitizer.sanitize(:sign_up)
    end
    def account_update_params
      devise_parameter_sanitizer.sanitize(:account_update)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


before_action :find_post
 before_action :find_comment, only: [:destroy, :edit , :update]
def create
@comment = @post.comments.create(params[:comment].permit(:content))
@comment.save
if @comment.save
  redirect_to post_path(@post)
else
  redirect_to post_path(@post), notice: 'Post failed pls post some thing'
end
end

def destroy
@comment.destroy
redirect_to post_path(@post)
end

def edit

end

def update
if @comment.update(params[:comment].permit(:content))
  redirect_to post_path(@post)
  else
    render 'edit'
  end
end



private
def find_post
  
  @post = Post.find(params[:post_id])
end

def find_comment
  @comment = @post.comments.find(params[:id])
end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to posts_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  def index
    @search = Post.search(params[:q])
    if params[:q]
      @posts=@search.result.order(:content).page(params[:page]).per(2)
    else
      @posts = Post.all.order("created_at DESC").page(params[:page])
    
    end
  end

  def show
    @comments = Comment.where(post_id: @post)
  end

  def new
    @post = Post.new
  
  end


  def edit
  end
  # def confirm
  #   @post = Post.new(blog_params)
  #   @post.user_id = current_user.id
  #   render :new if @post.invalid?
  # end

  def create
    @post = Post.new(post_params)
    # @post = current_user.posts.new(post_params[:post])
    @post.user_id = current_user.id
      if @post.save
         redirect_to @post, notice: 'Post was successfully created.' 
      else
       render :new 
      end
  end

  def update
      if @post.update(post_params)
         redirect_to @post, notice: 'Post was successfully updated.' 
      else
        render :edit 
      end
  end
  def destroy
    @post.destroy
     redirect_to posts_url, notice: 'Post was successfully destroyed.' 
  end

  private
   
    def set_post
      @post = Post.find(params[:id])
    end

    
    def post_params
      params.require(:post).permit(:tittle, :image, :content, :categories)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<ul>
  <% @comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <p><br><%= comment.content %><br>
        <% if user_signed_in? && current_user.id%>
        <%= link_to "delete", [comment.post, comment], method: :delete, class:"genric-btn danger-border circle" %>
        <%= link_to "edit ", edit_post_comment_path(comment.post, comment), class:"genric-btn success-border circle" %></p>
        </li>
        <% end %>
    <% end %>
  <% end %>
<%= render 'comments/form'%>
</ul>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>

<%= f.text_area :content, class:"single-input", placeholder:"enter comment"%>
<%= f.submit "post comment", class:"genric-btn info-border circle" %>

  <%end%>

app/views/comments/comment.js.erb
("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.post.comments, post: @comment.post }) %>")
("textarea").val('')

app/views/comments/create.html.erb
<h1>Comments#create</h1>

app/views/comments/edit.html.erb
<div class="container">


<%= form_for ([@post, @comment]) do |f| %>

    <%= f.text_area :content, class:"single-input"%>
    <%= f.submit "post comment", class:"genric-btn info-border circle" %>
    
      <%end%>

      </div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.post.comments, post: @comment.post }) %>")
$("textarea").val('')

app/views/home/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<section class="banner_part postt">

    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">

            <div class="carousel-caption text-dark text-left">
            <h2 class="animated fadeInLeft ">you lost ur i.d card to worry</h2>
            <p class="animated fadeInUp">this platform come to help the one lost their document to get it </p>
            <p class="animated fadeInUp">   <%= link_to 'view more posts',posts_path, class:"btn btn-transparent btn-rounded btn-large border border-dark"  %></p>
       </div>

            <%= image_tag("bannnero.png")%>
            </div>

            <div class="carousel-item">

            <div class="carousel-caption text-dark text-left">
            <h2 class="animated fadeInLeft ">you lost ur atm card or passport to worry</h2>
            <p class="animated fadeInUp">this platform come to help the one lost their document to get it in easy way </p>
            <p class="animated fadeInUp">   <%= link_to 'view more posts',posts_path, class:"btn btn-transparent btn-rounded btn-large border border-dark"  %></p>
       </div>

            <%= image_tag("bannner1.png")%>
            </div>
            <div class="carousel-item">
            <div class="carousel-caption text-dark text-left">
            <h2 class="animated fadeInLeft ">you lost ur college document to worry</h2>
            <p class="animated fadeInUp">this platform come to help the one lost their document to get it in easy way </p>
            <p class="animated fadeInUp">   <%= link_to 'view more posts',posts_path, class:"btn btn-transparent btn-rounded btn-large border border-dark"  %></p>
       </div>
            <%= image_tag("bannner3.png")%>
                
            </div>
           
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<!--::blog_part end::-->
<div class="section-top-border bob container">
				<h3 class="mb-30">Dive into code</h3>
				<div class="row">
					<div class="col-lg-12">
						<blockquote class="generic-blockquote">
							“Be able to pass the task with the cooperation of a mentor
                            Once the curriculum is complete, 
                            we will create a portfolio of tasks to practice 
                            what you have learned. There are only tasks that 
                            can not be passed in a straight line, but examine it 
                            yourself, organize the mistakes, and what you can not do, 
                                This works with the guidance of a mentor through questions 
                                and answers cycle.
                                Become able to develop an original application
                    After completing all the curriculums, 
                         as a compilation, in parallel with preparation for job hunting activities, 
                         we will develop a portfolio that showcases your abilities. 
                         Make good use of what you have learned so
                     far to succeed your graduation and employment.”
						</blockquote>
					</div>
				</div>
			</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Originproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">

    <link rel="icon" href="img/favicon.png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- animate CSS -->
    <link rel="stylesheet" href="css/animate.css">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <!-- themify CSS -->
    <link rel="stylesheet" href="css/themify-icons.css">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="css/flaticon.css">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="css/magnific-popup.css">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="css/slick.css">
    <!-- style CSS -->
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


    <style> 
    /* Modify the background color */ 
      
    .navbar-custom { 
        background-color: white; 
    } 
    /* Modify brand and text color */ 
      
    .navbar-custom .navbar-brand, 
    .navbar-custom .navbar-text { 
        color: green; 
    } 
</style> 

  </head>
  

  <body>

  <div class="container">

  <!--::header part start::-->
  <header class="main_menu home_menu sticky-top">
      <div class="container">
          <div class="row align-items-center">
              <div class="col-lg-12">
                  <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
 <%= image_tag("kl.png")%> 
                      <button class="navbar-toggler" type="button" data-toggle="collapse"
                          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                          aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                      </button>

                      <div class="collapse navbar-collapse main-menu-item justify-content-end"
                          id="navbarSupportedContent">
                          <ul class="navbar-nav align-items-center">
                          
                              <li class="nav-item active">
                                  <%= link_to 'Home',  root_path, class:'nav-link' %>
                              </li>
                                          <li class="nav-item">
                                <%= link_to 'Posts',posts_path, class:"nav-link"  %>
                        
                              </li>
                              
                              <% if current_user %>
                              <li class="nav-item dropdown">
                                  <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      My page
                                  </a>
                                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                      <%= link_to 'Edit Profile',edit_user_registration_path, class:'dropdown-item' %>
                                      <%= link_to 'Logout', destroy_user_session_path, class:'dropdown-item', method: :delete %>
                                  
                                  </div>
                              </li>
                              <% else %>
 
                              <li class="nav-item">
                              <%= link_to 'Log in',   new_user_session_path, class:'nav-link' %></li>
                              <li class="nav-item">
                                  <%= link_to 'Sing up',  new_user_registration_path, class:'nav-link' %>
                              </li>
                              <% end %>
                          </ul>
                      </div>
                  </nav>
              </div>
          </div>
      </div>
  </header>
  <!-- Header part end-->

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<!-- jquery plugins here-->
<!-- jquery -->
<script src="jquery-1.12.1.min.js"></script>
<!-- popper js -->
<script src="popper.min.js"></script>
<!-- bootstrap js -->
<script src="bootstrap.min.js"></script>
<!-- easing js -->
<script src="jquery.magnific-popup.js"></script>
<!-- swiper js -->
<script src="swiper.min.js"></script>
<!-- swiper js -->
<script src="masonry.pkgd.js"></script>
<!-- particles js -->
<script src="owl.carousel.min.js"></script>
<script src="jquery.nice-select.min.js"></script>
<!-- swiper js -->
<script src="slick.min.js"></script>
<script src="jquery.counterup.min.js"></script>
<script src="waypoints.min.js"></script>
<!-- custom js -->
<script src="custom.js"></script>



<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5 container ">

  <div style="background-color: #21d192;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left bg-light">

    <!-- Grid row -->
    <div class="row mt-3 dark-grey-text ">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold bg-light">Dive into coe original app</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Become able to develop an original application
        After completing all the curriculums, as a compilation, in parallel with preparation for job hunting activities, we will develop a portfolio that showcases your abilities. Make good use of what you have learned so far to succeed your graduation and employment.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 bg-light">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Products</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="dark-grey-text" href="https://diveintocode.jp/en_web_engineer_job">Dive into code</a>
        </p>
        <p>
        <%= link_to 'view more posts',posts_path, class: "dark-grey-text"  %>
        </p>
        <p>
        <%= link_to 'view more posts',posts_path, class: "dark-grey-text"  %>
        </p>
        <p>
        <%= link_to 'Sign up',new_user_registration_path, class:"dark-grey-text"  %>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 bg-light">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Useful links</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
        <%= link_to 'view more posts',posts_path, class:'dark-grey-text'  %>
        </p>
        <p>
        <%= link_to 'view more posts',posts_path, class:'dark-grey-text'  %>
        </p>
        <p>
        <%= link_to 'view more posts',posts_path, class:'dark-grey-text'  %>
        </p>
        <p>
        <%= link_to 'view more posts',posts_path, class:'dark-grey-text'  %>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> Kigali Rwanda</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> janvier@wayimboneye.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
        <p>
          <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center text-black-50 py-3 bg-light">© 2019 Copyright: Dive into code original application
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</div>  




</body>
</html>

app/views/posts/_form.html.erb
<!-- learning part start-->
<section class="advance_feature learning_part bob1">
    <div class="container">
        <div class="row align-items-sm-center align-items-xl-stretch">
            <div class="col-md-6 col-lg-6">
                <div class="learning_member_text">
               
                <h2>Wayimboneye online platform post</h2>
                <%= form_with(model: post, local: true) do |form| %>
                  <% if post.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
                
                      <ul>
                      <% post.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <% if user_signed_in?  %>
                  <%= form.hidden_field :user_id, value: current_user.id %>
                  <%end%>
                <div class="field">
                  <h5><%= form.label :image %></h5>
                  <%= form.file_field :image, class:"single-input"%>
                </div>
                  <div class="field mt-30">
                  <h5 ><%= form.label :tittle %></h5>
                  <%= form.text_field :tittle, class:"single-input", placeholder:"tittle" %>
                </div>
                <div class="field mt-30">
                  <h5 ><%= form.label :content %></h5>
                  <%= form.text_area :content, class:"single-textarea", placeholder:"Message" %>
                </div>
                 
                  <div class="field single-element-widget mt-30">
                    <h5><%= form.label :categories, class:'' %></h5>
                    <%= form.select :categories, ['', 'I.D', 'Driving Lisence', 'Diplome']  %>
                  </div>
                
                  <div class="actions  mt-30" >
                    <%= form.submit "post", class:"genric-btn success circle" %>
                  </div>
                <% end %>
                
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="learning_img">
                <%= image_tag("advance_feature_img.png")%>
                   
                </div>
            </div>
        </div>
    </div>
</section>
<!-- learning part end-->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container"> 
<% if  signed_in? %>
<%= link_to 'New Post', new_post_path, class:'btn rounded btn-primary' %>
<% if  current_user.admin == true %>
<%= link_to 'Admin_Dashboard',  rails_admin.dashboard_path, class:'btn rounded btn-primary' %>
<%end%>
<%end%>
<span class="position-relative">
<%=search_form_for @search do |f| %>                     
    <div class="input-group">
    <%= f.text_field :tittle_or_categories_cont, class:'single-input  col-sm-3', placeholder:"search" %>
     <%= f.submit "Search" , class:"genric-btn info-border circle" %> 
</div>
 <% end %>
</span>
 </div>

  <div class="card-columns mt-10 container">
  <% @posts.each do |post| %> 
  <div class="card">
  <%= image_tag(post.image , class:'card-img-top', style: "max-height: 18rem;" ) if post.image.attached? %>
  
  <div class="card-body">
  <b> Title: <%= post.tittle %> </b>
    <h5 class="card-title">Cat:<%= post.categories %></h5>
                       <%= link_to 'More Details', post %>      
                        <% if user_signed_in? && current_user.id == post.user_id %>
                        <%= link_to 'Edit', edit_post_path(post) %>
                        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                        <%end%>
                      
                        <small class="text-muted"><%= Comment.where(post_id: post.id).count %>comments</small>
</div>
  <div class="card-footer ">
    <small class="text-muted">posted at: <%= time_ago_in_words(post.created_at) %> 

    </small>
  </div>
</div>
<% end %>
  </div>
<!--::blog_part end::-->


<br>




<%= paginate @posts %>

app/views/posts/new.html.erb
<h1 class="text-center">New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
  
  <div class="container">
  
  <div class="card mt-20 " style= "max-height: 60rem; width: 30rem; left:20rem;">
  <%= image_tag(@post.image , class:'card-img-top', style: "max-height: 18rem;" ) if @post.image.attached? %>
  <div class="card-body">
    <h5 class="card-title"><p id="notice"><%= notice %></p>
    <b> Title: <%= @post.tittle %> </b>
   
    <br>
    <small class="text-muted">posted at: <%= @post.created_at %></small>
    <p><strong>post</strong>：<br><%= @post.content %></p></h5>
    <p class="card-text">
    <!-- Get an HTML id of this comments_area and update only the part of that div -->
  
<%= render 'comments/comment' %>



  <div class="card-footer ">
  <% if current_user ==  signed_in? %>

  <%= link_to 'Edit', edit_post_path(@post) %>
  <%end%>
  </div>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
 <b> <%= link_to "Sign up", new_registration_path(resource_name) %><br /></b>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <b><%= link_to "Forgot your password?", new_password_path(resource_name) %><br /></b>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>